### ISSUE TITLE
Support for hex encoded input

### ISSUE THREAD

**Issue by nicexe** [dmarman/sha256algorithm#1]
Not really an issue, more like a feature request.

It would be nice to also be able to enter a hex-string as an input.

**Comment by dmarman** [comment]
So this has been requested a few times already.

Added and deployed here https://github.com/dmarman/sha256algorithm/commit/43f698c8f04a9bd8a0720b96c3fd99e1bd480fb8

When switching bases the input conversion may be wonky with not standard UTF-8 values, couldn't figure out if this is a bug or a concept error. 
SHA256 calculations still correct, so for now I will accept it like that.
