### ISSUE TITLE
Icons for controls don't match their purpose

### ISSUE THREAD

**Issue by JonathonReinhart** [dmarman/sha256algorithm#2]
Awesome visualization!

I found some of the controls to be a little surprising, compared to a typical CD/DVD/video player. Here are the actions, their current icons, and a suggested icon that I think more people would expect:

| Action | Current Icon | Expected Icon | Notes | 
|------|--------------|---------------|----------|
| Auto Play | ![image](https://user-images.githubusercontent.com/1916566/152865308-c2c66422-c418-4f5a-a70b-26c78719b1c0.png) | ![image](https://user-images.githubusercontent.com/1916566/152865649-0100348f-fb07-4524-804a-ec69593537c8.png)  | This is just a normal "play" operation |
| Skip forward 10 | ![image](https://user-images.githubusercontent.com/1916566/152864035-03b11986-50dc-45b2-8ac9-45f00ea0dab8.png) | ![image](https://user-images.githubusercontent.com/1916566/152864083-1cccd233-e723-4dda-99fe-8057dadc4a0d.png) | On audio/video controls this would be "fast forward" |
| Jump to the end | ![image](https://user-images.githubusercontent.com/1916566/152864083-1cccd233-e723-4dda-99fe-8057dadc4a0d.png) | ![image](https://user-images.githubusercontent.com/1916566/152864035-03b11986-50dc-45b2-8ac9-45f00ea0dab8.png) | On a CD player this would be "go to next track"; the vertical line represents the track separator. Here it might represent the "end". | 
| Single step |  ![image](https://user-images.githubusercontent.com/1916566/152866737-5417134f-7212-4e94-9424-eeb3acde0275.png) | ![image](https://user-images.githubusercontent.com/1916566/152866577-546e2a60-815e-4548-a431-ffdd97ca4b27.png) | The double vertical bars imply "paused" |

(the same apply to the reverse direction as well).

References:
- https://thediagram.com/17_4/correct.html
- ![image](https://user-images.githubusercontent.com/1916566/152867164-2407944f-0e86-4802-9347-09de389af1fd.png)

**Comment by dmarman** [comment]
Thanks for the detailed explanation and the references! 
I knew I was doing something wrong here :)

Fixed and live with https://github.com/dmarman/sha256algorithm/commit/ee94db28a57e695d0547b56461d3d95048968940

**Comment by JonathonReinhart** [comment]
The new controls look great and make much more sense!
