### ISSUE TITLE
Question about computed SHA

### ISSUE THREAD

**Issue by samebchase** [dmarman/sha256algorithm#4]
Hi, love your visualisation!

I have a question, when I pass in the input `this`, I get the result as `1eb79602411ef02cf6fe117897015fff89f80face4eccd50425c45149b148408`, however when I do it the "usual" way:

```
# Mac
❯ echo 'this' | sha256sum
c18d547cafb43e30a993439599bd08321bea17bfedbe28b13bce8a7f298b63a2  -

# OpenBSD
$ echo 'this' | sha256
c18d547cafb43e30a993439599bd08321bea17bfedbe28b13bce8a7f298b63a2
```

Could you please confirm?

**Comment by bpycinski** [comment]
Indeed, great visualization. `echo` appends a '\n' character to the message. To omit this, run `echo -n this`.

**Comment by samebchase** [comment]
Oh wow, TIL! Thanks @bpycinski
